# trajectory generated by Raimund Dutzler
from PyQt4 import QtCore

class Anim(QtCore.QTimer):
    def __init__(self,cg,go):
        QtCore.QTimer.__init__(self)
        self.cg_=cg
        self.go_=go
        self.frame_=0
        QtCore.QObject.connect(self, QtCore.SIGNAL("timeout()"), self.OnTimer)

        
    def OnTimer(self):
        self.frame_=(self.frame_+1)%self.cg_.GetFrameCount()
        self.cg_.CopyFrame(self.frame_)
        go.UpdatePositions()


# old-style CHARMM format, requires flag bit 0 set
cg = io.LoadCHARMMTraj("mpor_trj.crd","mpor_trj_short.trj",1)
eh=cg.GetEntity()
go=gfx.Entity("test",eh.CreateFullView())

scene.Add(go)
scene.SetCenter(go.GetCenter())
scene.AutoAutoslab(True)

anim=Anim(cg,go)
anim.start(10)
